### ISSUE TITLE
No log in option after uninstall

### ISSUE THREAD

**Issue by CamiloGTR** [Telios-org/email-client-desktop#72]
### Description

I uninstalled Telios, and re-installed. Now the window only has the option to "Create an Account" and thus I'm unable to log in to my account.

### Steps to reproduce

1. Uninstall the client. 
2. Install the client.
3. No login option. 

### Environment details

Windows 10 + Custom build. 
Telios Version: v0.8.564

### Expected behavior

The welcome screen should have the options to login and to create an account. 

### Screenshots / Videos / Additional Details
![SNAG-0152](https://user-images.githubusercontent.com/16406219/182084038-455e6e19-81e0-41a2-905a-ada5fed82892.jpg)

**Comment by hexadecible** [comment]
This happens when you have no accounts in your accounts folder. On Windows this is normally stored on `C:\Users\you\App Data\Roaming\Telios\Accounts`. You should also know that if you install Telios on another machine, the Accounts directory will be empty because accounts are device bound at the moment. 

It's possible that when you uninstalled Telios, you uninstalled the app and all of the App Data. Our next release will allow account recovery and sync between devices so this shouldn't happen again.
